version: '2'
services:
  homepage:
    image: kelvv/nvmhome-docker:v1.1.5
    ports:
      - "0.0.0.0:3000:22"
      - "0.0.0.0:81:3000"
      - "0.0.0.0:3101:3100"
    environment:
      - NODE_ENV=staging
      - projecturl=https://github.com/kelvv/my-site.git
      - autoupdate=true
    container_name: kelvv-homepage
    restart: always

  shadowsock:
    image: kelvv/shadowsock-docker
    ports:
      - "0.0.0.0:7878:431"
    environment:
      - password=docker
    container_name: kelvv-shadowsock
    restart: always

  ppt:
    image: kelvv/nvmhome-docker:v1.1.5
    ports:
      - "0.0.0.0:82:3000"
      - "0.0.0.0:3102:3100"
    environment:
      - projecturl=https://github.com/kelvv/my-ppt.git
      - autoupdate=true
    container_name: kelvv-ppt
    restart: always
