version: '2'
services:
  shadowsock:
    image: kelvv/shadowsock-docker
    ports:
      - "0.0.0.0:7878:431"
    environment:
      - password=docker
    container_name: kelvv-shadowsock
    restart: always
  homepage:
    image: kelvv/nvmhome-docker
    ports:
      - "0.0.0.0:3000:22"
      - "0.0.0.0:80:3000"
    environment:
      - NODE_ENV = staging
      - projecturl = https://github.com/kelvv/my-site.git
    container_name: kelvv-homepage
    restart: always
